"""empty message

Revision ID: 2a8b76709e7e
Revises: 19bf194a9407
Create Date: 2015-05-15 23:52:02.277440

"""

# revision identifiers, used by Alembic.
revision = '2a8b76709e7e'
down_revision = '19bf194a9407'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('branch', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('deploy_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('repo_url', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'project', ['repo_url'])
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'])
    op.drop_column('project', 'logo')
    op.add_column('project_user', sa.Column('is_owner', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_user', 'is_owner')
    op.add_column('project', sa.Column('logo', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'user_id')
    op.drop_column('project', 'updated_at')
    op.drop_column('project', 'repo_url')
    op.drop_column('project', 'deploy_at')
    op.drop_column('project', 'created_at')
    op.drop_column('project', 'branch')
    ### end Alembic commands ###
