"""empty message

Revision ID: 37e278a2f0b5
Revises: 2a8b76709e7e
Create Date: 2015-05-29 01:22:59.996735

"""

# revision identifiers, used by Alembic.
revision = '37e278a2f0b5'
down_revision = '2a8b76709e7e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.models import Server
from sqlalchemy_utils import IPAddressType, ChoiceType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', ChoiceType(Server.ROLES), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('ssh_login', sa.String(length=255), nullable=True),
    sa.Column('ip_address', IPAddressType(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_deploy',
    sa.Column('deploy_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deploy_id'], ['deploy.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    op.drop_table('project_build')
    op.drop_table('build')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('number', mysql.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], [u'project.id'], name=u'build_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('project_build',
    sa.Column('build_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['build_id'], [u'build.id'], name=u'project_build_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], [u'project.id'], name=u'project_build_ibfk_2'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('project_deploy')
    op.drop_table('server')
    op.drop_table('deploy')
    ### end Alembic commands ###
